// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"resource/internal/biz"
	"resource/internal/conf"
	"resource/internal/data"
	"resource/internal/server"
	"resource/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	instanceRepo := data.NewResourceRepo(dataData, logger)
	auditRepo := data.NewAuditRepo(dataData, logger)
	k8sClient, err := data.NewK8sClient(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	k8sRepo, err := data.NewK8sRepo(confData, k8sClient, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	networkRepo := data.NewNetworkRepo(dataData, logger)
	execRepo := data.NewExecRepo(k8sClient, logger)
	resourceUsecase := biz.NewResourceUsecase(instanceRepo, auditRepo, k8sRepo, networkRepo, execRepo, logger)
	resourceService := service.NewResourceService(resourceUsecase)
	httpServer := server.NewHTTPServer(confServer, resourceService, logger)
	grpcServer := server.NewGRPCServer(confServer, resourceService, logger)
	connection, cleanup2, err := data.NewRabbitMQ(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mqServer := server.NewMQServer(confData, connection, resourceService, logger)
	app := newApp(logger, httpServer, grpcServer, mqServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
